//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.01 at 11:20:28 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://addressbook.com/contact", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.addressbook.wsdlClasses;
