//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.13 at 04:14:43 PM IST 
//


package com.addressbook.wsdlClasses;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.addressbook.wsdlClasses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.addressbook.wsdlClasses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddContactRequest }
     * 
     */
    public AddContactRequest createAddContactRequest() {
        return new AddContactRequest();
    }

    /**
     * Create an instance of {@link ContactInfoWithoutId }
     * 
     */
    public ContactInfoWithoutId createContactInfoWithoutId() {
        return new ContactInfoWithoutId();
    }

    /**
     * Create an instance of {@link AddContactResponse }
     * 
     */
    public AddContactResponse createAddContactResponse() {
        return new AddContactResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link ContactInfo }
     * 
     */
    public ContactInfo createContactInfo() {
        return new ContactInfo();
    }

    /**
     * Create an instance of {@link GetContactByIdRequest }
     * 
     */
    public GetContactByIdRequest createGetContactByIdRequest() {
        return new GetContactByIdRequest();
    }

    /**
     * Create an instance of {@link GetContactByIdResponse }
     * 
     */
    public GetContactByIdResponse createGetContactByIdResponse() {
        return new GetContactByIdResponse();
    }

    /**
     * Create an instance of {@link GetAllContactRequest }
     * 
     */
    public GetAllContactRequest createGetAllContactRequest() {
        return new GetAllContactRequest();
    }

    /**
     * Create an instance of {@link GetAllContactResponse }
     * 
     */
    public GetAllContactResponse createGetAllContactResponse() {
        return new GetAllContactResponse();
    }

    /**
     * Create an instance of {@link DeleteContactRequest }
     * 
     */
    public DeleteContactRequest createDeleteContactRequest() {
        return new DeleteContactRequest();
    }

    /**
     * Create an instance of {@link DeleteContactResponse }
     * 
     */
    public DeleteContactResponse createDeleteContactResponse() {
        return new DeleteContactResponse();
    }

    /**
     * Create an instance of {@link UpdateContactRequest }
     * 
     */
    public UpdateContactRequest createUpdateContactRequest() {
        return new UpdateContactRequest();
    }

    /**
     * Create an instance of {@link UpdateContactResponse }
     * 
     */
    public UpdateContactResponse createUpdateContactResponse() {
        return new UpdateContactResponse();
    }

}
